### ISSUE TITLE
Requirement: Mark areas that have been fired upon

### ISSUE THREAD

**Issue by warreq** [warreq/battlechat#4]
User story
----------------

*As a Player,*
I would like to be able to see where my fleet has already shot at,
**so that** I can keep track of where to shoot next and avoid wasting shots.

                         |   Acceptance test
--------------------|-----------------------------------------------------------------------------------
Prerequisites      | Player has fired at least one shot |
Expected Input   | Player chooses to fire their shot on a square that they've already hit |
Expected Output | The ability to select that square is disabled |

**Comment by TheMightyMarm** [comment]
**
